apiVersion: apps/v1
kind: Deployment
metadata:                            # metadat for replicaset
  name: test-deployment
  labels:
    app: test
    type: java-app
    env: prod

spec:                               # specification for replicaset
 template:
    metadata:                       # metadata for template
      name: test-pod
      labels:
        app: test
        type: java-app
        name: test-pod
    spec:                          # specification for template
     containers:
      - name: test-container
        imagePullPolicy: Always
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
 replicas: 3                     # number of replica has to be create under this replicaset
 selector:                       # describe to select and monitor the filtered pods. It can be created by this replicaset or not
    matchLabels:
     name: test-pod
     app: test